config/routes.rb
Rails.application.routes.draw do
  get 'fosters/create'
  devise_for :users
  root to: "pets#index"
  resources :shelters
  resources :pets, only: [:index, :show, :new, :create, :update, :edit] do
    resources :fosters, only: [:new, :create]
    end
  # resources :users, only: [:show, :new, :create]
  resources :users, only: [:show, :new, :create, :update, :edit]

  delete 'pets/:id', to: 'pets#destroy', as: 'delete_pet'
  delete 'shelters/:id', to: 'shelters#destroy', as: 'delete_shelter'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foster.rb
class Foster < ApplicationRecord
  belongs_to :pet
  belongs_to :user
end

app/models/pet.rb
class Pet < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :shelter
  #belongs_to :user, through: :shelters
  has_many :fosters, dependent: :destroy
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :pets, dependent: :destroy
  before_destroy :check_for_pets

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  private

  def check_for_pets
    if pets.count.positive?
      raise_error
      return false
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :photo, PhotoUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shelters, dependent: :destroy
  has_many :fosters
  has_many :pets_at_shelter, through: :shelters, source: :pets
  has_many :pets, through: :fosters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(pets_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/fosters_controller.rb
class FostersController < ApplicationController

  def new
    @foster = Foster.new()
    authorize @foster
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @foster = Foster.new(pet: @pet, user: current_user)
    day = Date.today.to_s
    @foster.date = day
    @pet.status = "fostered"
    authorize @foster
    @pet.save
    if @foster.save
      redirect_to pet_path(@foster.pet_id), notice: "You're now fostering this pet"
    else
      render @pet
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :find_pet, only: [ :show, :update, :edit, :destroy]

  def index
    # @pets = Pet.all
    if params[:query].present?
      # @pets = policy_scope(Pet).where("name ILIKE ?", "%#{params[:query]}%")
      sql_query = "\
      name ILIKE :query \
      OR age::text ILIKE :query \
      OR status ILIKE :query \
      OR sociability ILIKE :query \
      OR breed ILIKE :query \
      "
      @pets = policy_scope(Pet).where(sql_query, query: "%#{params[:query]}%")
    else
      @pets = policy_scope(Pet).order(created_at: :desc)
    end
  end

  def show
  end

  def new
    @pet = Pet.new
    @my_shelters = Shelter.where(user: current_user.id)
    authorize @pet
    # @shelter = Shelter.find(params[:shelter_id])
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.shelter = Shelter.find(params[:pet][:shelter_id])
    @pet.status = "available"
    authorize @pet
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def update
    @pet.update(pet_params)
    authorize @pet
    redirect_to pet_path(@pet)
  end

  def edit
  end

  def destroy
    @pet.destroy
    authorize @pet
    redirect_to pets_path
  end

  private

  def find_pet
    @pet = Pet.find(params[:id])
    authorize @pet
  end

  def pet_params
    params.require(:pet).permit(:name, :age, :breed, :size, :sociability, :status, :activity_level, :shelter_id, :description, :good_with_other_pets, :good_with_kids, :hypoallergenic, :photo)
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  before_action :find_shelter, only: [:show, :edit, :update, :destroy]

  def index
    @shelters = policy_scope(Shelter).order(created_at: :desc)
  end

  def show
    @pets = @shelter.pets
    #@shelter_with_coord = @shelter.where.not(latitude: nil, longitude: nil)
    if @shelter.latitude
      @markers = [{lat: @shelter.latitude,lng: @shelter.longitude}]
    end
  end

  def new
    @shelter = Shelter.new
    authorize @shelter
  end

  def create
    @shelter = Shelter.new(shelter_params)
    @shelter.user = current_user
    current_user.shelter_owner = true
    authorize @shelter
    if @shelter.save && current_user.save
      redirect_to shelter_path(@shelter)
    else
      render :new
    end
  end

  def update
    @shelter.update(shelter_params)
    redirect_to shelter_path(@shelter)
  end

  def edit
  end

  def destroy
    @shelter.destroy
    redirect_to shelters_path
  end

  private

  def find_shelter
    @shelter = Shelter.find(params[:id])
    authorize @shelter
  end

  def shelter_params
    params.require(:shelter).permit(:name, :address, :phone_number, :user_id, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to pets_path
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def edit
  end

  private

  def find_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:name, :description, :phone_number, :shelter_owner, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fosters/create.html.erb
<h1>Input a New Foster Pup</h1>

app/views/fosters/new.html.erb
<div class = "form-container">
<div class = "container-headline">
<div class="inner-form-container">
<%= simple_form_for [@foster], url: pet_fosters_path do |f| %>
  <%= f.input :date, as: :date, html5: true%>
  <%= f.submit "Foster this pet!", class: "btn btn-info" %>
<% end %>
  </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- < stylesheet_pack_tag 'application', media: 'all' %> -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/pet.html.erb
<div class="container pet-container pet-name"><% @pet.name %></div>

<div class="container pet-container pet-description"><%= @pet.description %></div>

<div class="container pet-container pet-details">
  <ul>
    <li class="no-bullets"><% @pet.breed %></li>
    <li class="no-bullets"><% @pet.size %></li>
    <li class="no-bullets"><% @pet.age %></li>
    <li class="no-bullets"><% @pet.activity_level %></li>
    <li class="no-bullets"><% @pet.sociability %></li>
  </ul>
</div>

<div class="container">
  <%= image_tag "" alt: "Pet Photo" class: "pet-profile" %>
</div>


<div class="container pet-container"><% @pet.status %></div>
<div class="btn btn-info pet-btn">FOSTER ME</div>

app/views/pets/_form.html.erb
<%= simple_form_for(pet) do |f| %>
  <!-- [...] -->
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <!-- [...] -->
<% end %>

app/views/pets/edit.html.erb
<div class='form-container'>
<div class = "container-headline">
<h1>Edit Pet</h1>
<div class='inner-form-container'>
    <div class='form-container-arrangement'>

      <%= form_for(@pet) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :breed %>
          <%= f.text_field :breed, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :size %>
          <%= f.text_field :size, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :age %>
          <%= f.text_field :age, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :activity_level %>
          <%= f.text_field :activity_level, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :sociability %>
          <%= f.text_field :sociability, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :hypoallergenic %>
          <%= f.text_field :hypoallergenic, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :good_with_kids %>
          <%= f.text_field :good_with_kids, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :good_with_other_pets %>
          <%= f.text_field :good_with_other_pets, class: 'form-control' %>
        </div>


        <div class="form-group">
          <%= f.label :photo %>
          <%= f.file_field :photo, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description  %>
          <%= f.text_field :description , class: 'form-control' %>
        </div>

        <div class='form-group'> <%= f.submit class: 'btn btn-info'%></div>

        <div class='delete-link form-group'><%= link_to 'Delete pet', pet_path(@pet),
        method: :delete,
        data: { confirm: "Are you sure?" }, class: 'btn btn-info' %>
      </div>
      <div class='link-back form-group'><%= link_to "Back to list", pets_path, class: 'btn btn-info' %></div>

      <% end %>

  </div>
</div>
</div>
</div>

app/views/pets/index.html.erb
<div  style="width: 100%">
   <div class="home-banner" style="background-image: linear-gradient(-90deg, rgba(0,0,0,0.45) 0%, rgba(0,0,0,0.4) 50%), url('<%= image_path 'FOSTR-BANNER.jpg' %>');">
    <div class="banner-content">
      <strong> <h1>Welcome to FOSTR</h1> </strong>
      <p>Find Your Perfect Foster Pup</p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @pets.each do |pet| %>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <%= link_to "", pet_path(pet)%>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url('<%= pet.photo.url.nil? ? "placeholder" : cl_image_path(pet.photo.url, width: 400, height: 500, crop: :fill) %>')">
        <%= link_to "", pet_path(pet), class: 'card-link' %>
        <div class="card-description" class ="card-label">
          <%= pet.name %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
 </div>

app/views/pets/new.html.erb
<div class = "container-headline">
  <h1>Add a Pet To Foster</h1>
  <div class = "form-container">
    <div class="inner-form-container">
      <div>
        <%= simple_form_for(@pet) do |f| %>
          <!-- [...] -->
          <%= f.input :name %>
          <%= f.input :breed %>
          <%= f.input :size, collection: ['Small', 'Medium', 'Large'] %>
          <%= f.input :age, collection: 0..20 %>
          <%= f.input :activity_level, collection: ['Low', 'Medium', 'High'] %>
          <%= f.input :sociability, collection: ['Low', 'Medium', 'High'] %>
          <%= f.input :hypoallergenic, collection: ['Yes', 'No'] %>
          <%= f.input :good_with_kids, collection: ['Yes', 'No'] %>
          <%= f.input :good_with_other_pets, collection: ['Yes', 'No'] %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.input :description %>
          <%= f.association :shelter, collection: @my_shelters %>
          <!-- f.association :shelter, collection: Shelter.where(user: @user) -->
          <%= f.button :submit, class: 'btn btn-info' %>
          <!-- [...] -->
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<!-- <h1>Pets#show</h1>
  <p>Find me in app/views/pets/show.html.erb</p> -->

  <div class="container page">
    <div class="row">
      <!-- left side of page with name of pet, their description and details section -->
      <div class="col-8">
        <div class="title pet-name"><strong><%= @pet.name.upcase %></strong></div>
          <br>
          <div class="container pet-container pet-details">
            <ul>
              <li class = "no-bullets" id="no-titleize"><strong>Description: </strong><%=@pet.description%></li>
              <br>
              <div class="d-flex justify-content-start">
                <div class="left-set">
                  <li class="no-bullets"><strong>Breed: </strong><%=@pet.breed.capitalize %></li>
                  <li class="no-bullets"><strong>Size: </strong><%=@pet.size.capitalize %></li>
                  <li class="no-bullets"><strong>Age: </strong><%=@pet.age %></li>
                  <li class="no-bullets"><strong>Activity Level: </strong><%=@pet.activity_level.capitalize %></li>
                </div>
                <div class="right-set" style="margin-left: 80px;">
                  <li class="no-bullets"><strong>Sociability: </strong><%=@pet.sociability.capitalize %></li>
                  <li class="no-bullets"><strong>Good With Kids: </strong>
                    <%= if @pet.good_with_kids
                        "Yes"
                      else
                        "No"
                      end %></li>
                  <li class="no-bullets"><strong>Good With Other Pets: </strong>
                    <%= if @pet.good_with_other_pets
                        "Yes"
                      else
                        "No"
                      end %></li>
                  <li class="no-bullets"><strong>Hypoallergenic: </strong>
                    <%= if @pet.hypoallergenic
                        "Yes"
                      else
                        "No"
                      end %></li>
                </div>
              </div>
            </ul>
         </div>
       </div>
      <!-- right side of page with photo, foster status and button to initiate foster -->
      <div class="col-4 text-center">
        <div class = "container-photo">
        <div class="pet-photo">
          <%= cl_image_tag @pet.photo, height: 500, crop: :fill %>
        </div>
          <div class="pet-container" id = "my-pet-shelter">
            <strong><%= @pet.status.capitalize %></strong>
            <br>
            <%= link_to "My shelter", shelter_path(@pet.shelter) %>
          </div>

          <div class="btn btn-info pet-btn"><%= link_to "FOSTER ME", new_pet_foster_path(@pet), class: "link_text"%></div>

          <% if policy(@pet).edit? %>
            <div class="btn edit-btn btn-info link_text" id="link_text">
              <%= link_to "Edit", edit_pet_path, class: "link_text" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div>
    <%= link_to pets_path, class: "navbar-brand" do %>
    <!-- using a placeholder image for now - need a logo design -->
    <%= image_tag "fostr-icon.jpg", alt: "FOSTR", class: "avatar-bordered" %>
    <% end %>
    <%= form_tag pets_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for a pet name, age, breed or availability"
      %>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <div class="navbar-wagon-right hidden-xs hidden-sm">
        <div class="navbar-wagon-item navbar-wagon-link"><%= link_to "Add a shelter", new_shelter_path%></div>
        <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">My Fosters</a> -->
        <a class="navbar-wagon-item navbar-wagon-link"><%=current_user.name? ? current_user.name : current_user.email%></a>
      </div>
      <li class="nav-item dropdown">
        <%= image_tag "person.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Account", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shelters/edit.html.erb
<div class='form-container'>
  <div class='container-headline'>
      <h1>Edit Shelter</h1>
      <div class='inner-form-container'>
        <div class='form-container-arrangement'>


          <%= form_for(@shelter) do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :phone_number %>
            <%= f.text_field :phone_number, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_field :description, class: 'form-control' %>
          </div>

          <div class='form-group'> <%= f.submit class: 'btn btn-info'%></div>

          <div class='delete-link form-group'><%= link_to 'Delete Shelter', pets_path,
          method: :delete,
          data: { confirm: "Are you sure?" } , class: 'btn btn-info' %>
        </div>

        <div class='link-back form-group'><%= link_to "Back to Shelter", shelter_path(@shelter), class: 'btn btn-info' %></div>

        <% end %>
    </div>
  </div>
</div>
</div>

app/views/shelters/index.html.erb
<h1>Shelters#index</h1>
<p>Find me in app/views/shelters/index.html.erb</p>

app/views/shelters/new.html.erb
<div class = "form-container">
<div class = "container-headline">
<h1>Add A New Shelter</h1>
<div class="inner-form-container">
<%= simple_form_for(@shelter) do |f| %>
  <!-- [...] -->
  <%= f.input :name %>
  <%= f.input :address, id: 'shelter_address' %>
  <%= f.input :phone_number %>
  <%= f.input :description %>
  <%= f.button :submit, class: 'btn btn-info' %>
  <!-- [...] -->
<% end %>
  </div>
</div>
</div>
</div>

app/views/shelters/show.html.erb
<div class="container page">
  <div class="row">


    <!-- left side of page with name of shelter, description and pet cards -->
    <div class="col-8">
      <!-- top section of left side: name, description and details -->
      <div class="row">
        <div class="col-12">
          <div class="title pet-name"><strong><%= @shelter.name.upcase %></strong></div>
          <div class="container pet-container pet-description"><%= @shelter.description %></div>

        </div>
      </div>

      <!-- bottom section of left side: pet cards of pets currently available at this shelter -->
      <div class="row">
        <div class="col-12">
          <h2 class="section">Pets currently available at <%= @shelter.name.titleize %></h2>
          <div class="row">
            <% @shelter.pets.each do |pet| %>
              <div class="col-xs-12 col-sm-6 col-md-4">
                <%= link_to "", pet_path(pet), class: 'card-link' %>
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url('<%= pet.photo.url.nil? ? "placeholder" : cl_image_path(pet.photo.url, width: 400, height: 500, crop: :fill) %>')">
                  <%= link_to "", pet_path(pet), class: 'card-link' %>
                  <div class="card-description" class ="card-label">
                    <%= pet.name %>
                     <!-- <%= link_to 'Delete pet', pet_path(pet), method: :delete, data: { confirm: "Are you sure?" } %> -->
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <!-- right side of page with map, shelter address and contact info -->
    <div class="col-4 text-center">
      <div class = "container-photo">
        <div class="map">
          <!-- INSERT MAP HERE -->
          <div
          id="map"
          style="width: 100%;
          height: 500px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>
        </div>
      </div>
      <div class='shelter-details'>
        <ul>
          <li class="no-bullets"><strong>Address: </strong><%=@shelter.address.capitalize %></li>
          <li class="no-bullets"><strong>Phone Number: </strong><%=@shelter.phone_number %></li>
        </ul>

        <% if policy(@shelter).edit? %>
        <div class="btn edit-btn btn-info">
          <%= link_to "Edit Shelter", edit_shelter_path(@shelter),class: "link_text" %>
        </div>
        <% end %>

        <% if policy(@shelter).edit? %>
        <div class="btn edit-btn btn-info" id="new-pet">
          <%= link_to "Add a Pet", new_pet_path, class: "link_text" %>
        </div>
        <% end %>

      </div>
    </div>


  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class='form-container'>
  <div class='container-headline'>
      <h1>Edit Account Details</h1>
      <div class='inner-form-container'>
        <div class='form-container-arrangement'>


          <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

           <div class="form-group">
            <%= f.label :shelter_owner %>
            <%= f.text_field :shelter_owner, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_field :description, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :phone_number %>
            <%= f.text_field :phone_number, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :photo %>
            <%= f.file_field :photo, class: 'form-control' %>
          </div>

          <div class='form-group'> <%= f.submit class: 'btn btn-info'%></div>

          <div class='delete-link form-group'><%= link_to 'Delete Account', pets_path,
          method: :delete,
          data: { confirm: "Are you sure?" } , class: 'btn btn-info' %>
        </div>

        <div class='link-back form-group'><%= link_to "Back to Profile", user_path(@user), class: 'btn btn-info' %></div>

        <% end %>
    </div>
  </div>
</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container page">
  <div class="row">


    <!-- left side of page with name of shelter, description and pet cards -->
    <div class="col-8">

    <!-- top section of left column with name, description, admin status and associated shelters -->
      <div class="row">
        <div class="col-12">
          <div class="title pet-name"><strong><%= @user.name.titleize %></strong></div>
          <div class="container pet-container pet-description"><%= @user.description.capitalize %></div>

          <!-- <% if @user.admin %>
            <div class="admin-tag">admin</div>
          <% end %>

          <% if @user.shelter_owner %>
            <div class="btn" id="shelter-btn">
              <% @user.shelters.each do |shelter| %>
              <%= link_to shelter.name, shelter_path(shelter) %>
            </div>
          <% end %>
          <% end %>
        -->
        </div>
      </div>

      <!-- bottom section of left side: pet cards of pets currently fostered by this user -->
      <div class="row">
        <div class="col-12">
          <h2 class="section">Pets currently being fostered by <%= @user.name.titleize %></h2>
          <div class="row">
            <% @user.pets.each do |pet| %>
              <div class="col-xs-12 col-sm-6 col-md-4">
                <%= link_to "", pet_path(pet), class: 'card-link' %>
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url('<%= pet.photo.url.nil? ? "placeholder" : cl_image_path(pet.photo.url, width: 400, height: 500, crop: :fill) %>')">
                  <%= link_to "", pet_path(pet), class: 'card-link' %>
                  <div class="card-description" class ="card-label">
                    <%= pet.name %>
                     <!-- <%= link_to 'Delete pet', pet_path(pet), method: :delete, data: { confirm: "Are you sure?" } %> -->
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>


    </div>




    <!-- right side of page with map, shelter address and contact info -->
    <div class="col-4 text-center">
      <div class = "container-photo">
        <div class="pet-photo">
          <%= cl_image_tag @user.photo, height: 500, crop: :fill %>
        </div>
      </div>
      <div class='shelter-details'>
        <p>Contact</p>
        <ul>
          <li class="no-bullets"><strong>Email: </strong><%=@user.email.downcase %></li>
          <li class="no-bullets"><strong>Phone: </strong><%=@user.phone_number %></li>
        </ul>
        <% if policy(@user).edit? %>
        <div class="btn edit-btn">
          <%= link_to "Edit Account", edit_user_path(@user) %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>